#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 11 22:42:01 2021

@author: thierry
"""

### Window
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 800
win_size = f"{WINDOW_WIDTH}x{WINDOW_HEIGHT}"

### Main Frame
MAINFRAME_WIDTH = 1000
MAINFRAME_CENTRE_X = MAINFRAME_WIDTH / 2
MAINFRAME_HEIGHT = 600
MAINFRAME_CENTRE_Y = MAINFRAME_HEIGHT / 2
OFFSET_MAINFRAME_X = 10
OFFSET_MAINFRAME_Y = 10
MAINFRAME_TOP_Y = 50

### Score Frame
SCOREFRAME_WIDTH = 370
SCOREFRAME_CENTRE_X = SCOREFRAME_WIDTH / 2
SCOREFRAME_HEIGHT = 600
SCOREFRAME_CENTRE_Y = SCOREFRAME_HEIGHT / 2
OFFSET_SCOREFRAME_X = 1020
OFFSET_SCOREFRAME_Y = 10
SCOREFRAME_TOP_X = SCOREFRAME_CENTRE_X
SCOREFRAME_TOP_Y = 50
SCOREFRAME_BEVUE_Y =  SCOREFRAME_HEIGHT - (SCOREFRAME_HEIGHT / 4)

### Citation Frame
CITATIONFRAME_WIDTH = 980
CITATIONFRAME_CENTRE_X = CITATIONFRAME_WIDTH / 2
CITATIONFRAME_HEIGHT = 100
CITATIONFRAME_CENTRE_Y = CITATIONFRAME_HEIGHT / 2
OFFSET_CITATIONFRAME_X = 20
OFFSET_CITATIONFRAME_Y = 500

### Notice Frame
NOTICEFRAME_WIDTH = 1380
NOTICEFRAME_CENTRE_X = NOTICEFRAME_WIDTH / 2
NOTICEFRAME_HEIGHT = 170
NOTICEFRAME_CENTRE_Y = NOTICEFRAME_HEIGHT / 2
OFFSET_NOTICEFRAME_X = 10
OFFSET_NOTICEFRAME_Y = 620
NOTICEFRAME_TOP_X = NOTICEFRAME_CENTRE_X
NOTICEFRAME_TOP_Y = OFFSET_NOTICEFRAME_Y + 50


### Widget geometry
SIZE_ENTRY = 30
SIZE_BUTTON = 5

OFFSET_BUTTON = 25
OFFSET_TEXT = 25

